version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

      - restore_cache:
          key: node_modules_{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: yarn

      - save_cache:
          key: node_modules_{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Prettier
          command: yarn fmt-errors

      - run:
          name: Test
          command: yarn test --runInBand

      - run:
          name: Build
          command: yarn build

      - persist_to_workspace:
          root: .
          paths:
            - build/

  deploy:
    docker:
      - image: circleci/python:3.7

      - attach_workspace:
          at: .

      - run:
          name: Install AWS cli
          command: sudo pip install awscli

      - run:
          name: Deploy
          command: aws s3 sync ./build/ s3://acharlton-mathmo/



workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: org-global

      - deploy:
          context: org-global
          requires:
            - test
          filters:
            branches:
              only: master
