version: 2
jobs:
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

      - restore_cache:
          key: node_modules_{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: yarn

      - save_cache:
          key: node_modules_{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Prettier
          command: yarn fmt-errors

      - run:
          name: Test
          command: yarn test --runInBand


workflows:
  version: 2
  build_and_test:
    jobs:
      - test
